###############################################################################
# Joseph Zambreno               
# Department of Electrical and Computer Engineering
# Iowa State University
###############################################################################

###############################################################################
# Makefile for building an OpenGL software application
###############################################################################


# Executable name
EXECUTABLE := 01_ClearTest

# C source files (separated by spaces)
CFILES := 01_ClearTest.c
CPPFILES := 

# Additional include directories
INCLUDE_PATH := -I. 

# Additional link library directories
LIB_PATH := -L.

# Additional link libraries
#LIB := -lm

###############################################################################
# Rules and targets

include ../../../common/common.mk
