###############################################################################
# Joseph Zambreno               
# Department of Electrical and Computer Engineering
# Iowa State University
###############################################################################

###############################################################################
# Makefile for building an OpenGL software application
###############################################################################


# Executable name
EXECUTABLE := 02_simpleshader

# C source files (separated by spaces)
CFILES := 02_simpleshader.c
CPPFILES := 

# Additional include directories
INCLUDE_PATH := -I. 

# Additional link library directories
LIB_PATH := -L.

# Additional link libraries
#LIB := -lm

###############################################################################
# Rules and targets

include ../../../common/common.mk
