# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
