# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/HW/480/Mp-0/hw/proj/mvmac.runs/synth_1/mvmac.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/HW/480/Mp-0/hw/proj/mvmac.cache/wt [current_project]
set_property parent.project_path E:/HW/480/Mp-0/hw/proj/mvmac.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {E:/HW/480/Mp-0/hw/board} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo e:/HW/480/Mp-0/hw/proj/mvmac.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  E:/HW/480/Mp-0/sw/dmem.dat
  E:/HW/480/Mp-0/sw/outmem.dat
}
read_verilog -library xil_defaultlib {
  E:/HW/480/Mp-0/hw/src/user/dmem.v
  E:/HW/480/Mp-0/hw/src/fixed/outmem.v
  E:/HW/480/Mp-0/hw/src/fixed/uart_Controller.v
}
read_vhdl -library xil_defaultlib {
  E:/HW/480/Mp-0/hw/src/fixed/uart/baud_cnt.vhd
  E:/HW/480/Mp-0/hw/src/fixed/bin_to_ascii.vhd
  E:/HW/480/Mp-0/hw/src/fixed/fixed_logic.vhd
  E:/HW/480/Mp-0/hw/src/fixed/uart/mmu_uart_top.vhd
  E:/HW/480/Mp-0/hw/src/fixed/uart/rx.vhd
  E:/HW/480/Mp-0/hw/src/fixed/uart/tx.vhd
  E:/HW/480/Mp-0/hw/src/user/user_logic.vhd
  E:/HW/480/Mp-0/hw/src/mvmac.vhd
}
read_ip -quiet E:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xci
set_property used_in_implementation false [get_files -all e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo.xdc]
set_property used_in_implementation false [get_files -all e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/HW/480/Mp-0/hw/src/fixed/uart/fifo/fifo_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/HW/480/Mp-0/hw/constrs/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files E:/HW/480/Mp-0/hw/constrs/NexysVideo_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mvmac -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mvmac.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mvmac_utilization_synth.rpt -pb mvmac_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
